Repository MyLittleTranscendence/ft_transcendence, pull requests merged in 2024-02, with the labels that each got.

#90 feat(user): check 문서화
  backend/backend/urls.py
  backend/user/serializers.py
  backend/user/views.py
Labels: enhancement

#91 [Frontend] 메인페이지 UI 구현
  frontend/Index.html
  frontend/asset/icon_people.svg
  frontend/asset/pingpong_racket.png
  frontend/src/components/LobbyPage/ChatInput.js
  frontend/src/components/LobbyPage/GlobalChatContainer.js
  frontend/src/components/LobbyPage/MatchContainer.js
  frontend/src/components/LobbyPage/MatchTypeDropdown.js
  frontend/src/components/LobbyPage/SideBar.js
  frontend/src/components/UI/BouncingBallOnRacket.css
  frontend/src/components/UI/BouncingBallOnRacket.js
  frontend/src/components/UI/Button/Button.js
  frontend/src/components/UI/Container/PageContainerWithLogo.js
  frontend/src/components/UI/Icon/FriendsIcon.js
  frontend/src/components/UI/Profile/ProfileImage.css
  frontend/src/components/UI/Profile/ProfileImage.js
  frontend/src/pages/JincparkTestPage.js
  frontend/src/pages/LobbyPage.js
Labels: enhancement

#94 feat(custom_auth): backend auth 코드 리팩토링 및 테스트
  backend/backend/settings.py
  backend/custom_auth/serializers.py
  backend/custom_auth/views.py
  backend/user/models.py
Labels: enhancement, refactor

#95 [Frontend] 회원가입 페이지 UI 구현
  frontend/src/components/Form/SignUpForm.js
  frontend/src/components/UI/Button/Button.js
  frontend/src/pages/SignUpPage.js
Labels: enhancement

#98 [Frontend] 사용자는 웹사이트에 안전하게 가입할 수 있습니다
  frontend/src/components/Form/SignUpForm.js
  frontend/src/core/Component.js
  frontend/src/handlers/api/signUpHandler.js
  frontend/src/utils/fetch/fetchAPI.js
Labels: enhancement

#99 [Frontend] 등록된 사용자는 안전하게 로그인할 수 있습니다
  frontend/src/components/Landing/SignInLink.css
  frontend/src/components/Landing/SignInLink.js
  frontend/src/components/Lobby/ChatInput.js
  frontend/src/components/Lobby/GlobalChatContainer.js
  frontend/src/components/Lobby/MatchContainer.js
  frontend/src/components/Lobby/MatchTypeDropdown.js
  frontend/src/components/Lobby/SideBar.js
  frontend/src/components/SignIn/SignInForm.js
  frontend/src/components/SignUp/SignUpForm.js
  frontend/src/components/UI/Button/Button.js
  frontend/src/components/UI/Input/InfoInputGroup.js
  frontend/src/handlers/api/signInHandler.js
  frontend/src/pages/JincparkTestPage.js
  frontend/src/pages/LandingPage.js
  frontend/src/pages/LobbyPage.js
  frontend/src/pages/SignInPage.js
  frontend/src/pages/SignUpPage.js
Labels: enhancement

#102 [Frontend] 2차인증 UI
  frontend/src/components/SignIn/TwoFAForm.js
  frontend/src/pages/JincparkTestPage.js
Labels: enhancement

#104 [Frontend] 프로필 UI 컴포넌트 구현
  frontend/src/components/Profile/Overview.css
  frontend/src/components/Profile/Overview.js
  frontend/src/components/Profile/Profile.js
  frontend/src/pages/ProfilePage.js
Labels: enhancement

#107 docs(login): 디폴트 로그인 반환값 문서화
  backend/custom_auth/views.py
Labels: documentation

#109 feat(oauth): oauth 로그인시 쿼리파라미터 전달
  backend/custom_auth/views.py
Labels: enhancement

#111 feat(oauth): oauth 로그인시 user_id, mfa_require 전달
  backend/custom_auth/views.py
Labels: enhancement

#113 refactor(custom_auth): backend jwt httponly 쿠키 방식으로 사용하는 것으로 커스텀
  backend/backend/settings.py
  backend/backend/urls.py
  backend/custom_auth/middleware.py
  backend/custom_auth/serializers.py
  backend/custom_auth/views.py
Labels: enhancement, refactor

#118 feat(chat): 전체채팅 기능 구현
  backend/chat/consumers.py
  backend/chat/templates/chat/room.html
Labels: enhancement

#121 feat(custom_auth): code 발급시 이메일주소 전송
  backend/custom_auth/serializers.py
  backend/custom_auth/views.py
Labels: enhancement

#122 feat(chat): 단일 채팅 기능 구현
  backend/chat/consumers.py
  backend/chat/templates/chat/room.html
Labels: enhancement

#126 feat(block): 사용자 차단목록 모델 개발
  backend/backend/settings.py
  backend/block/__init__.py
  backend/block/admin.py
  backend/block/apps.py
  backend/block/migrations/__init__.py
  backend/block/models.py
  backend/block/tests.py
  backend/block/views.py
Labels: enhancement

#114 [Frontend] 전적 UI 구현
  frontend/src/components/Landing/SignInLink.js
  frontend/src/components/Profile/MatchHistoryCard.css
  frontend/src/components/Profile/MatchHistoryCard.js
  frontend/src/components/Profile/Overview.js
  frontend/src/pages/ProfilePage.js
Labels: enhancement

#128 feat(block): backend 사용자 차단 차단 해제 api 개발
  backend/backend/urls.py
  backend/block/models.py
  backend/block/serializers.py
  backend/block/views.py
Labels: enhancement

#130 feat(chat): 1:1 메시지 차단기능 추가
  backend/chat/consumers.py
Labels: enhancement

#133 feat(friend): backend 친구 모델 추가
  backend/backend/settings.py
  backend/friend/__init__.py
  backend/friend/admin.py
  backend/friend/apps.py
  backend/friend/migrations/__init__.py
  backend/friend/models.py
  backend/friend/tests.py
  backend/friend/views.py
Labels: enhancement

#135 feat(friends): backend 친구 관리 api 추가
  backend/backend/urls.py
  backend/friend/models.py
  backend/friend/serializers.py
  backend/friend/views.py
Labels: enhancement

#139 [Frontend] 일반 로그인 시 mfa 페이지 접근 안됨
  frontend/src/api/auth/fetchSignIn.js
  frontend/src/api/auth/fetchSignInTwoFA.js
  frontend/src/core/router.js
  frontend/src/pages/TwoFAPage.js
Labels: bug

#143 [Frontend] 로그인 페이지에 경고문구 기능 구현
  frontend/src/api/auth/fetchSignIn.js
  frontend/src/components/SignIn/SignInForm.js
  frontend/src/components/UI/Input/InputGroup.js
  frontend/src/handlers/signInHandler.js
Labels: enhancement

#146 feat(chat): socket 접속, 해제시 자신을 친구로 추가한 유저들에게 알림
  backend/chat/consumers.py
Labels: enhancement

#151 [Backend] user get api email, username 필드 제거
  backend/user/serializers.py
Labels: refactor

#153 [Backend] oauth 로그인 시 is_new_user 여부 쿼리 파리미터로 반환
  backend/custom_auth/serializers.py
  backend/custom_auth/views.py
Labels: refactor

#147 [Frontend] 토스트 UI 구현
  frontend/Index.html
  frontend/src/api/auth/fetchDisableTwoFA.js
  frontend/src/api/auth/fetchEnableTwoFA.js
  frontend/src/api/auth/fetchSendCode.js
  frontend/src/api/auth/fetchSignIn.js
  frontend/src/api/auth/fetchSignInTwoFA.js
  frontend/src/api/auth/fetchSignUp.js
  frontend/src/api/user/fetchUserInfo.js
  frontend/src/components/Toast/Toast.css
  frontend/src/components/Toast/Toast.js
  frontend/src/core/router.js
  frontend/src/utils/fetchAPI.js
  frontend/src/utils/showToast.js
Labels: enhancement

#161 [Backend] chat 소켓 문서화
  backend/backend/urls.py
  backend/chat/consumers.py
  backend/chat/views.py
Labels: documentation

#162 docs(chat): chat 소켓 문서화 수정
  backend/chat/views.py
Labels: documentation

#163 [Backend] chat 소켓 문서화 수정
  backend/chat/views.py
Labels: bug

#167 [Backend] oauth 로그인시 유저 파라미터 전달
  backend/custom_auth/views.py
Labels: enhancement

#169 [Frontend] me api 추가에 따른 수정 및 oauth 가입 유저 닉네임 설정 구현
  frontend/src/App.js
  frontend/src/api/auth/fetchDisableTwoFA.js
  frontend/src/api/auth/fetchEnableTwoFA.js
  frontend/src/api/auth/fetchSendCode.js
  frontend/src/api/auth/fetchSignIn.js
  frontend/src/api/auth/fetchSignInTwoFA.js
  frontend/src/api/auth/fetchSignUp.js
  frontend/src/api/user/fetchMyInfo.js
  frontend/src/api/user/fetchNickname.js
  frontend/src/api/user/fetchUserInfo.js
  frontend/src/components/Landing/SignInLink.js
  frontend/src/components/Start/SignInLink.css
  frontend/src/components/Start/SignInLink.js
  frontend/src/components/UI/Link/Link.js
  frontend/src/core/router.js
  frontend/src/core/routes.js
  frontend/src/handlers/setNicknameHandler.js
  frontend/src/pages/LobbyPage.js
  frontend/src/pages/SetNicknamePage.js
  frontend/src/pages/StartPage.js
  frontend/src/utils/fetchAPI.js
Labels: enhancement

#171 [Frontend] 사용자는 다른 사용자에게 직접 메시지를 보낼 수 있어야 합니다 - 전체 채팅
  frontend/Index.html
  frontend/global.css
  frontend/src/components/Lobby/ChatInput.js
  frontend/src/components/Lobby/GlobalChatContainer.js
  frontend/src/components/Lobby/GlobalMessage.js
  frontend/src/components/UI/Profile/ProfileImage.css
  frontend/src/handlers/sendMessageHandler.js
  frontend/src/pages/LobbyPage.js
  frontend/src/socket/chatSocket.js
  frontend/src/utils/formatTime.js
Labels: enhancement

#173 [backend] single game 개발
  backend/backend/consumers.py
  backend/backend/redis.py
  backend/chat/consumers.py
  backend/custom_auth/views.py
  backend/game/consumers.py
  backend/game/message_type.py
  backend/game/service.py
  backend/game/templates/game/index.html
  backend/game/templates/game/room.html
  backend/game/templates/game/single_game.html
  backend/game/urls.py
  backend/game/views.py
Labels: enhancement

#180 [Backend] 큐 삭제 로직 개발
  backend/game/consumers.py
  backend/game/message_type.py
  backend/game/service.py
  backend/game/templates/game/multi_game.html
  backend/game/templates/game/tournament_game.html
Labels: enhancement

#182 [Frontend] 게임 페이지 UI 구현
  frontend/global.css
  frontend/src/components/Game/GameCanvas.js
  frontend/src/components/Game/NextMatchBox.js
  frontend/src/components/Game/PlayerOverview.js
  frontend/src/components/Game/PlayerOverviews.js
  frontend/src/components/Game/PongGame.js
  frontend/src/components/Game/PvPReady.js
  frontend/src/components/Game/TournamentReady.js
  frontend/src/components/Lobby/GlobalChatContainer.js
  frontend/src/components/UI/Profile/ProfileImage.css
  frontend/src/pages/PvPGamePage.js
  frontend/src/pages/TournamentGamePage.js
Labels: enhancement

#183 [Backend] 매칭 수락 로직 개발
  backend/game/consumers.py
  backend/game/message_type.py
  backend/game/service.py
  backend/game/templates/game/multi_game.html
  backend/game/templates/game/tournament_game.html
Labels: enhancement

#185 [Backend] 게임 api 추가
  backend/backend/urls.py
  backend/game/models.py
  backend/game/serializers.py
  backend/game/service.py
  backend/game/views.py
  backend/user/serializers.py
Labels: enhancement

#189 [Backend] info에서 맵사이즈 공사이즈 바 사이즈 정보 제공
  backend/game/consumers.py
  backend/game/service.py
  backend/game/views.py
  backend/user/serializers.py
Labels: enhancement

#196 [Backend] 게임 소켓 문서화
  backend/backend/urls.py
  backend/chat/views.py
  backend/game/message_type.py
  backend/game/service.py
  backend/game/views.py
Labels: enhancement

#191 [Frontend] 전역 상태 관리 구현
  frontend/src/api/auth/fetchDisableTwoFA.js
  frontend/src/api/auth/fetchEnableTwoFA.js
  frontend/src/api/user/fetchMyInfo.js
  frontend/src/pages/JincparkTestPage.js
  frontend/src/store/initialStates.js
  frontend/src/store/observer.js
  frontend/src/store/store.js
Labels: enhancement

#198 [Frontend] component 렌더링 방식 수정
  frontend/src/App.js
  frontend/src/components/Game/PlayerOverviews.js
  frontend/src/components/Game/PvPReady.js
  frontend/src/components/Game/TournamentReady.js
  frontend/src/components/Lobby/GlobalChatContainer.js
  frontend/src/components/Lobby/MatchContainer.js
  frontend/src/components/Lobby/SideBar.js
  frontend/src/components/SignIn/SignInForm.js
  frontend/src/components/SignIn/TwoFAForm.js
  frontend/src/components/SignUp/SignUpForm.js
  frontend/src/components/Start/SignInLink.js
  frontend/src/components/UI/Input/InputGroup.js
  frontend/src/core/Component.js
  frontend/src/pages/LobbyPage.js
  frontend/src/pages/SetNicknamePage.js
  frontend/src/pages/SignInPage.js
  frontend/src/pages/SignUpPage.js
  frontend/src/pages/StartPage.js
  frontend/src/pages/TwoFAPage.js
Labels: bug

#200 [Frontend] 매칭 섹션 상세 UI 구현
  frontend/src/components/Lobby/MatchContainer.js
  frontend/src/components/Lobby/MatchTypeDropdown.css
  frontend/src/components/Lobby/MatchTypeDropdown.js
  frontend/src/components/Lobby/TimeLeftBar.css
  frontend/src/components/UI/Button/Button.css
Labels: enhancement

#201 [Backend] 토너먼트 경기 정보 처음에 전달
  backend/backend/urls.py
  backend/game/consumers.py
  backend/game/message_type.py
  backend/game/service.py
  backend/game/views.py
Labels: enhancement

#203 [Backend] 채팅 메시지에 이미지 필드 추가
  backend/backend/settings.py
  backend/chat/consumers.py
  backend/chat/views.py
Labels: enhancement

#208 [Backend] 게임에 초대 기능 추가
  backend/backend/urls.py
  backend/game/consumers.py
  backend/game/message_type.py
  backend/game/service.py
  backend/game/templates/game/multi_game.html
  backend/game/views.py
Labels: enhancement

#209 [Bakcend] 이메일 변경시 mfa_enable false로 변경
  backend/user/serializers.py
Labels: enhancement

#207 feat: add sender profile image source
  frontend/src/components/Lobby/GlobalChatContainer.js
  frontend/src/components/Lobby/GlobalMessage.js
Labels: enhancement

#211 [Frontend] 컴포넌트 unmount 구현
  frontend/src/App.js
  frontend/src/api/user/fetchNickname.js
  frontend/src/components/Lobby/GlobalChatContainer.js
  frontend/src/components/Lobby/SideBar.js
  frontend/src/core/Component.js
  frontend/src/core/router.js
  frontend/src/handlers/sendMessageHandler.js
  frontend/src/pages/LobbyPage.js
  frontend/src/pages/SetNicknamePage.js
  frontend/src/pages/SignInPage.js
  frontend/src/pages/SignUpPage.js
  frontend/src/pages/TwoFAPage.js
  frontend/src/socket/chatSocket.js
  frontend/src/socket/socketManager.js
  frontend/src/store/store.js
  frontend/src/store/storeObserver.js
Labels: enhancement

#214 [Backend] 큐 인원수 알림 로직 추가
  backend/game/consumers.py
  backend/game/message_type.py
  backend/game/service.py
Labels: enhancement

#218 [Backend]게임 정보 저장시 승패 저장
  backend/game/models.py
  backend/game/service.py
  backend/game/templates/game/multi_game.html
  backend/user/models.py
Labels: enhancement

#223 [Backend] custom_auth 문서화 및 리팩토링
  backend/backend/checkers.py
  backend/backend/error_messages.py
  backend/backend/settings.py
  backend/custom_auth/authentication.py
  backend/custom_auth/middleware.py
  backend/custom_auth/oauth_service.py
  backend/custom_auth/serializers.py
  backend/custom_auth/services.py
  backend/custom_auth/views.py
  backend/requirements.txt
  backend/user/admin.py
  backend/user/models.py
Labels: documentation, refactor

#225 [Backend] block 문서화 및 리팩토링
  backend/backend/error_messages.py
  backend/block/models.py
  backend/block/views.py
  backend/custom_auth/authentication.py
Labels: documentation, refactor

#227 [Backend] friend: 문서화
  backend/backend/error_messages.py
  backend/friend/models.py
  backend/friend/views.py
Labels: documentation

#229 [Backend] chat 리팩토링 및 문서화
  backend/backend/consumers.py
  backend/block/models.py
  backend/chat/consumers.py
  backend/chat/views.py
  backend/friend/models.py
  backend/game/consumers.py
  backend/game/message_type.py
Labels: enhancement

#231 [Frontend] 마이페이지 UI 및 기능구현
  frontend/src/api/auth/fetchDisableTwoFA.js
  frontend/src/api/auth/fetchEnableTwoFA.js
  frontend/src/components/Lobby/MatchContainer.js
  frontend/src/components/Lobby/SideBar.js
  frontend/src/components/Profile/MatchHistoryCard.js
  frontend/src/components/Profile/MatchHistoryList.js
  frontend/src/components/Profile/Overview.js
  frontend/src/components/Profile/Profile.js
  frontend/src/components/Profile/Settings.js
  frontend/src/components/SignIn/TwoFAForm.js
  frontend/src/components/UI/Button/Button.js
  frontend/src/components/UI/Input/Input.js
  frontend/src/core/router.js
  frontend/src/core/routes.js
  frontend/src/handlers/disableTwoFAHandler.js
  frontend/src/handlers/emailUpdateHandler.js
  frontend/src/handlers/imageUpdateHandler.js
  frontend/src/handlers/nicknameUpdateHandler.js
  frontend/src/handlers/twoFAHandler.js
  frontend/src/pages/JincparkTestPage.js
  frontend/src/pages/MyPage.js
  frontend/src/pages/ProfilePage.js
  frontend/src/utils/fetchAPI.js
Labels: enhancement

#216 feat: add href to logo
  frontend/src/components/UI/Container/PageContainerWithLogo.js
Labels: enhancement

#233 [Backend] 사용자 정보 변경시 django channels에 알리기
  backend/backend/__init__.py
  backend/backend/apps.py
  backend/backend/consumers.py
  backend/backend/settings.py
  backend/backend/signals.py
  backend/chat/consumers.py
  backend/game/consumers.py
Labels: enhancement

#234 [Backend] game 리팩토링 및 문서화
  backend/backend/consumers.py
  backend/game/consumers.py
  backend/game/service.py
  backend/game/views.py
Labels: documentation, refactor

#236 212 frontend 매칭 관련 버튼 UI 수정
  frontend/src/components/Lobby/MatchContainer.js
  frontend/src/components/Lobby/MatchTypeDropdown.js
Labels: enhancement

#237 frontend 게임 소켓 게임 매치 메이킹 기능 구현
  frontend/src/App.js
  frontend/src/api/auth/fetchEnableTwoFA.js
  frontend/src/api/auth/fetchSendCode.js
  frontend/src/api/auth/fetchSignIn.js
  frontend/src/api/auth/fetchSignInTwoFA.js
  frontend/src/api/auth/fetchSignUp.js
  frontend/src/api/user/fetchMyInfo.js
  frontend/src/api/user/fetchNickname.js
  frontend/src/api/user/fetchUserInfo.js
  frontend/src/components/Game/NextMatchBox.js
  frontend/src/components/Game/PlayerOverview.js
  frontend/src/components/Game/PlayerOverviews.js
  frontend/src/components/Game/PongGame.js
  frontend/src/components/Game/PvPReady.js
  frontend/src/components/Lobby/GlobalChatContainer.js
  frontend/src/components/Lobby/MatchContainer.js
  frontend/src/components/Lobby/MatchTypeDropdown.css
  frontend/src/components/Lobby/SideBar.js
  frontend/src/components/Profile/MatchHistoryCard.js
  frontend/src/components/Profile/MatchHistoryList.js
  frontend/src/components/Profile/Profile.js
  frontend/src/components/Profile/Settings.js
  frontend/src/components/SignIn/SignInForm.js
  frontend/src/components/SignIn/TwoFAForm.js
  frontend/src/components/SignUp/SignUpForm.js
  frontend/src/core/router.js
  frontend/src/core/routes.js
  frontend/src/handlers/auth/disableTwoFAHandler.js
  frontend/src/handlers/auth/signInHandler.js
  frontend/src/handlers/auth/signUpHandler.js
  frontend/src/handlers/auth/twoFAHandler.js
  frontend/src/handlers/chat/sendChatHandler.js
  frontend/src/handlers/game/matchMakingHandlers.js
  frontend/src/handlers/user/emailUpdateHandler.js
  frontend/src/handlers/user/imageUpdateHandler.js
  frontend/src/handlers/user/nicknameUpdateHandler.js
  frontend/src/handlers/user/setNicknameHandler.js
  frontend/src/pages/LobbyPage.js
  frontend/src/pages/PongGamePage.js
  frontend/src/pages/ProfilePage.js
  frontend/src/pages/PvPGamePage.js
  frontend/src/pages/PvPReadyPage.js
  frontend/src/pages/SetNicknamePage.js
  frontend/src/pages/TournamentGamePage.js
  frontend/src/pages/TournamentReadyPage.js
  frontend/src/store/initialStates.js
  frontend/src/utils/fetchAPI.js
Labels: enhancement

#240 feat: 친구목록 UI 구현
  frontend/src/components/Friend/FriendsList.js
  frontend/src/components/Lobby/SideBar.js
Labels: enhancement

#242 [Frontend] 타 유저 프로필 및 친구추가 구현
  frontend/src/App.js
  frontend/src/api/user/fetchFriends.js
  frontend/src/api/user/fetchMyInfo.js
  frontend/src/components/Friend/FriendsList.js
  frontend/src/components/Lobby/SideBar.js
  frontend/src/components/Profile/Overview.js
  frontend/src/components/Profile/Profile.js
  frontend/src/core/router.js
  frontend/src/handlers/user/addFriendHandler.js
  frontend/src/handlers/user/deleteFriendHandler.js
  frontend/src/handlers/user/setNicknameHandler.js
  frontend/src/pages/LobbyPage.js
  frontend/src/pages/PongGamePage.js
  frontend/src/store/initialStates.js
Labels: enhancement

#243 [Backend] 기본 마이그레이션 파일 추가
  backend/game/migrations/__init__.py
Labels: bug, enhancement

#246 [Backend] 401 발생시 쿠키 즉시 만료
  backend/backend/exception_handler.py
Labels: enhancement

#248 [Backend] 로그아웃 기능 구현
  backend/backend/consumers.py
  backend/backend/exception_handler.py
  backend/backend/signals.py
  backend/backend/urls.py
  backend/chat/views.py
  backend/custom_auth/views.py
  backend/game/views.py
  backend/requirements.txt
Labels: enhancement

#251 [Backend] 중복 로그인 감지
  backend/backend/consumers.py
  backend/backend/signals.py
  backend/chat/views.py
  backend/game/views.py
Labels: enhancement

#252 [Backend] game info에서 토너먼트 다음 게임 유저 정보 전송
  backend/backend/asgi.py
  backend/backend/consumers.py
  backend/backend/middleware.py
  backend/chat/consumers.py
  backend/conftest.py
  backend/game/consumers.py
  backend/game/service.py
  backend/game/views.py
  backend/pyproject.toml
  backend/pytest.ini
  backend/requirements.txt
  backend/tests/__init__.py
  backend/tests/test_game_consumer.py
  backend/tests/test_socket_aute_middleware.py
Labels: enhancement

#254 [Backend] game info user_id 관련 필드 integer로 통일
  backend/game/service.py
  backend/game/views.py
Labels: refactor

#255 [Backend] cli 기능 추가 바 키우기
  backend/game/consumers.py
  backend/game/service.py
  backend/game/templates/game/multi_game.html
  backend/game/views.py
Labels: enhancement

#258 [Frontend] 프로필페이지 닉네임 수정 버튼 표시 버그
  frontend/src/api/auth/fetchEnableTwoFA.js
  frontend/src/components/Game/PlayerOverview.js
  frontend/src/components/Profile/Profile.js
  frontend/src/handlers/auth/disableTwoFAHandler.js
  frontend/src/handlers/user/emailUpdateHandler.js
Labels: bug

#260 feat: cli command done
  frontend/src/handlers/game/gameHandler.js
  frontend/src/pages/PongGamePage.js
Labels: enhancement

#262 chore: nginx reverse proxy
  backend/backend/settings.py
  docker-compose.yml
  frontend/default.conf
  frontend/src/socket/socketManager.js
  frontend/src/utils/fetchAPI.js
Labels: enhancement

#264 [Backend] profileimage 주소 버그 개선
  backend/backend/consumers.py
  backend/backend/settings.py
  backend/backend/urls.py
Labels: bug

#268 [Frontend] 1대1 신청 수신 시 모달
  frontend/src/components/Game/MultiGameResultModal.js
  frontend/src/components/Game/TournamentGameResultModal.js
  frontend/src/components/Lobby/GameInviteModal.js
  frontend/src/components/Lobby/MatchContainer.js
  frontend/src/components/UI/Modal/Modal.js
  frontend/src/components/UI/Toast/Toast.js
  frontend/src/handlers/game/matchMakingHandlers.js
Labels: enhancement

#271 [Backend] check api 버그 개선
  backend/user/views.py
Labels: bug

#267 feat: dm 컴포넌트 구현
  frontend/src/api/user/fetchBlockList.js
  frontend/src/components/Friend/BlockList.js
  frontend/src/components/Friend/BlockListModal.js
  frontend/src/components/Friend/DirectMessage.js
  frontend/src/components/Friend/DirectMessageContainer.js
  frontend/src/components/Friend/DirectMessageModal.js
  frontend/src/components/Friend/Friend.js
  frontend/src/components/Friend/FriendList.js
  frontend/src/components/Friend/FriendListModal.js
  frontend/src/components/Friend/FriendsList.js
  frontend/src/components/Lobby/ChatInput.js
  frontend/src/components/Lobby/GlobalChatContainer.js
  frontend/src/components/Lobby/SideBar.js
  frontend/src/components/UI/Icon/FriendIcon.js
  frontend/src/components/UI/Icon/OnlineIcon.js
  frontend/src/core/routes.js
  frontend/src/handlers/user/blockUserHandler.js
  frontend/src/handlers/user/unblockUserHandler.js
  frontend/src/pages/HyeonjunTestPage.js
  frontend/src/pages/LobbyPage.js
  frontend/src/store/initialStates.js
Labels: enhancement

#273 [Frontend] 입력값 유효성 검증
  frontend/src/components/Profile/Profile.js
  frontend/src/components/Profile/Settings.js
  frontend/src/components/SignIn/SignInForm.js
  frontend/src/components/SignUp/SignUpForm.js
  frontend/src/components/UI/Input/InputGroup.js
  frontend/src/handlers/user/emailUpdateHandler.js
  frontend/src/handlers/user/inputValidateHandlers.js
  frontend/src/handlers/user/nicknameUpdateHandler.js
Labels: enhancement

#275 [Frontend] 로그아웃 구현
  frontend/src/components/Profile/MatchHistoryList.js
  frontend/src/components/Profile/Profile.js
  frontend/src/handlers/auth/logoutHandler.js
Labels: enhancement

#276 [Frontend] logout 소켓 메시지 수신 시 logout api 호출
  frontend/src/components/Game/PongGame.js
  frontend/src/components/Lobby/GlobalChatContainer.js
  frontend/src/components/Lobby/MatchContainer.js
  frontend/src/handlers/auth/socketLogoutHandler.js
  frontend/src/handlers/chat/chatHandler.js
  frontend/src/pages/PongGamePage.js
Labels: enhancement

#278 feat: blocked user message filtering
  frontend/src/handlers/chat/chatHandler.js
Labels: enhancement

#279 feat: friendlist dropdown button logic
  frontend/src/App.js
  frontend/src/api/user/fetchBlockList.js
  frontend/src/api/user/fetchFriendList.js
  frontend/src/components/Friend/BlockList.js
  frontend/src/components/Friend/FriendList.js
  frontend/src/components/Game/SingleGameResultModal.js
  frontend/src/components/Lobby/MatchContainer.js
  frontend/src/handlers/game/inviteUserHandler.js
  frontend/src/handlers/user/unblockUserHandler.js
  frontend/src/pages/LobbyPage.js
Labels: enhancement

#283 [Backend]: dm 전송시 본인에게도 보내주기
  backend/chat/consumers.py
Labels: enhancement

#285 [Backend] 회원정보 수정시 이미지 주소 버그 개선
  backend/backend/signals.py
Labels: bug

#287 [Backend] 백엔드 포트 노출 해제
  backend/backend/settings.py
  backend/custom_auth/oauth_42_constant.py
  docker-compose.yml
  frontend/default.conf
  frontend/src/pages/StartPage.js
Labels: enhancement

#290 fix: 회원가입 및 전체채팅 오류 수정
  frontend/src/components/SignUp/SignUpForm.js
  frontend/src/handlers/chat/chatHandler.js
Labels: enhancement

#292 [Backend] 전체 채팅 차단 유저 메시지 필터링
  backend/backend/settings.py
  backend/backend/signals.py
  backend/block/models.py
  backend/chat/consumers.py
Labels: enhancement

#294 [Backend] 친구 목록 갱신 정보 시그널
  backend/backend/signals.py
  backend/chat/consumers.py
Labels: enhancement

#295 [Frontend] 내 프로필 페이지 프로필 이미지 호버 및 내 프로필 페이지 제외 모든 프로필 이미지에 프로필 페이지 링크 추가
  frontend/src/components/Friend/BlockList.js
  frontend/src/components/Friend/FriendList.js
  frontend/src/components/Lobby/GlobalMessage.js
  frontend/src/components/Lobby/SideBar.js
  frontend/src/components/Profile/MatchHistoryCard.js
  frontend/src/components/Profile/Profile.js
  frontend/src/components/UI/Profile/ProfileImage.css
  frontend/src/components/UI/Profile/ProfileImage.js
  frontend/src/pages/ProfilePage.js
Labels: enhancement

#297 feat: upgrade online icon & dm
  frontend/src/components/Friend/BlockList.js
  frontend/src/components/Friend/DirectMessageContainer.js
  frontend/src/components/Friend/DirectMessageModal.js
  frontend/src/components/Friend/Friend.js
  frontend/src/components/Friend/FriendList.js
  frontend/src/components/Lobby/ChatInput.js
  frontend/src/components/SignIn/SignInForm.js
  frontend/src/components/UI/Icon/OnlineIcon.js
  frontend/src/handlers/chat/onlineCheckHandler.js
  frontend/src/handlers/user/inputValidateHandlers.js
Labels: enhancement

#306 fix: tournament profile image
  frontend/src/pages/PongGamePage.js
Labels: bug

#310 [Frontend] 토너먼트 결과 모달 내 컨텐츠 표시 오류
  frontend/src/components/Game/TournamentGameResultModal.js
  frontend/src/components/UI/Profile/ProfileImage.js
  frontend/src/core/router.js
Labels: bug

#312 fix: always update my info on Profile page
  frontend/src/components/Profile/Profile.js
Labels: enhancement

#313 feat: 매치 히스토리 기능 추가
  frontend/src/components/Game/PlayerOverview.js
  frontend/src/components/Profile/MatchHistoryCard.css
  frontend/src/components/Profile/MatchHistoryCard.js
  frontend/src/components/Profile/Overview.js
Labels: enhancement
